/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CustomerRouteImport } from './routes/customer'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as BusinessesRouteImport } from './routes/businesses'
import { Route as BusinessRouteImport } from './routes/business'
import { Route as BecomeABusinessRouteImport } from './routes/become-a-business'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as BusinessesIndexRouteImport } from './routes/businesses.index'
import { Route as BusinessIndexRouteImport } from './routes/business.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as CustomerWishlistRouteImport } from './routes/customer.wishlist'
import { Route as CustomerSupportRouteImport } from './routes/customer.support'
import { Route as CustomerSettingsRouteImport } from './routes/customer.settings'
import { Route as CustomerProfileRouteImport } from './routes/customer.profile'
import { Route as CustomerNotificationsRouteImport } from './routes/customer.notifications'
import { Route as CustomerCheckoutRouteImport } from './routes/customer.checkout'
import { Route as CustomerCartRouteImport } from './routes/customer.cart'
import { Route as CustomerAddressesRouteImport } from './routes/customer.addresses'
import { Route as BusinessesIdRouteImport } from './routes/businesses.$id'
import { Route as BusinessTeamRouteImport } from './routes/business.team'
import { Route as BusinessStorefrontRouteImport } from './routes/business.storefront'
import { Route as BusinessSettingsRouteImport } from './routes/business.settings'
import { Route as BusinessServicesRouteImport } from './routes/business.services'
import { Route as BusinessReviewsRouteImport } from './routes/business.reviews'
import { Route as BusinessProductsRouteImport } from './routes/business.products'
import { Route as BusinessOrdersRouteImport } from './routes/business.orders'
import { Route as BusinessNotificationsRouteImport } from './routes/business.notifications'
import { Route as BusinessCustomersRouteImport } from './routes/business.customers'
import { Route as BusinessBookingsRouteImport } from './routes/business.bookings'
import { Route as BusinessBillingRouteImport } from './routes/business.billing'
import { Route as BusinessAnalyticsRouteImport } from './routes/business.analytics'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBusinessesRouteImport } from './routes/admin.businesses'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as CustomerOrdersIndexRouteImport } from './routes/customer.orders.index'
import { Route as CustomerBookingsIndexRouteImport } from './routes/customer.bookings.index'
import { Route as CustomerOrdersIdRouteImport } from './routes/customer.orders.$id'
import { Route as CustomerCheckoutSuccessRouteImport } from './routes/customer.checkout.success'
import { Route as CustomerBookingsIdRouteImport } from './routes/customer.bookings.$id'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRoute = CustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessesRoute = BusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessRoute = BusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeABusinessRoute = BecomeABusinessRouteImport.update({
  id: '/become-a-business',
  path: '/become-a-business',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRoute,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CustomerRoute,
} as any)
const BusinessesIndexRoute = BusinessesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessesRoute,
} as any)
const BusinessIndexRoute = BusinessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BusinessRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProductsRoute,
} as any)
const CustomerWishlistRoute = CustomerWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSupportRoute = CustomerSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerSettingsRoute = CustomerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerProfileRoute = CustomerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerNotificationsRoute = CustomerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckoutRoute = CustomerCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCartRoute = CustomerCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerAddressesRoute = CustomerAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => CustomerRoute,
} as any)
const BusinessesIdRoute = BusinessesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BusinessesRoute,
} as any)
const BusinessTeamRoute = BusinessTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessStorefrontRoute = BusinessStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessSettingsRoute = BusinessSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessServicesRoute = BusinessServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessReviewsRoute = BusinessReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessProductsRoute = BusinessProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessOrdersRoute = BusinessOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessNotificationsRoute = BusinessNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessCustomersRoute = BusinessCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessBookingsRoute = BusinessBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessBillingRoute = BusinessBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => BusinessRoute,
} as any)
const BusinessAnalyticsRoute = BusinessAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => BusinessRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBusinessesRoute = AdminBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const CustomerOrdersIndexRoute = CustomerOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerBookingsIndexRoute = CustomerBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerOrdersIdRoute = CustomerOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => CustomerRoute,
} as any)
const CustomerCheckoutSuccessRoute = CustomerCheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CustomerCheckoutRoute,
} as any)
const CustomerBookingsIdRoute = CustomerBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => CustomerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-a-business': typeof BecomeABusinessRoute
  '/business': typeof BusinessRouteWithChildren
  '/businesses': typeof BusinessesRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/customer': typeof CustomerRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/billing': typeof BusinessBillingRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/notifications': typeof BusinessNotificationsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/products': typeof BusinessProductsRoute
  '/business/reviews': typeof BusinessReviewsRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/storefront': typeof BusinessStorefrontRoute
  '/business/team': typeof BusinessTeamRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRouteWithChildren
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/products/$id': typeof ProductsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/checkout/success': typeof CustomerCheckoutSuccessRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/bookings/': typeof CustomerBookingsIndexRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/become-a-business': typeof BecomeABusinessRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/billing': typeof BusinessBillingRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/notifications': typeof BusinessNotificationsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/products': typeof BusinessProductsRoute
  '/business/reviews': typeof BusinessReviewsRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/storefront': typeof BusinessStorefrontRoute
  '/business/team': typeof BusinessTeamRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRouteWithChildren
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/products/$id': typeof ProductsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/admin': typeof AdminIndexRoute
  '/business': typeof BusinessIndexRoute
  '/businesses': typeof BusinessesIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/products': typeof ProductsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/checkout/success': typeof CustomerCheckoutSuccessRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/bookings': typeof CustomerBookingsIndexRoute
  '/customer/orders': typeof CustomerOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-a-business': typeof BecomeABusinessRoute
  '/business': typeof BusinessRouteWithChildren
  '/businesses': typeof BusinessesRouteWithChildren
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/customer': typeof CustomerRouteWithChildren
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/products': typeof ProductsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/bookings': typeof AdminBookingsRoute
  '/admin/businesses': typeof AdminBusinessesRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/business/analytics': typeof BusinessAnalyticsRoute
  '/business/billing': typeof BusinessBillingRoute
  '/business/bookings': typeof BusinessBookingsRoute
  '/business/customers': typeof BusinessCustomersRoute
  '/business/notifications': typeof BusinessNotificationsRoute
  '/business/orders': typeof BusinessOrdersRoute
  '/business/products': typeof BusinessProductsRoute
  '/business/reviews': typeof BusinessReviewsRoute
  '/business/services': typeof BusinessServicesRoute
  '/business/settings': typeof BusinessSettingsRoute
  '/business/storefront': typeof BusinessStorefrontRoute
  '/business/team': typeof BusinessTeamRoute
  '/businesses/$id': typeof BusinessesIdRoute
  '/customer/addresses': typeof CustomerAddressesRoute
  '/customer/cart': typeof CustomerCartRoute
  '/customer/checkout': typeof CustomerCheckoutRouteWithChildren
  '/customer/notifications': typeof CustomerNotificationsRoute
  '/customer/profile': typeof CustomerProfileRoute
  '/customer/settings': typeof CustomerSettingsRoute
  '/customer/support': typeof CustomerSupportRoute
  '/customer/wishlist': typeof CustomerWishlistRoute
  '/products/$id': typeof ProductsIdRoute
  '/services/$id': typeof ServicesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/business/': typeof BusinessIndexRoute
  '/businesses/': typeof BusinessesIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/customer/bookings/$id': typeof CustomerBookingsIdRoute
  '/customer/checkout/success': typeof CustomerCheckoutSuccessRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/bookings/': typeof CustomerBookingsIndexRoute
  '/customer/orders/': typeof CustomerOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/become-a-business'
    | '/business'
    | '/businesses'
    | '/categories'
    | '/contact'
    | '/cookies'
    | '/customer'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/business/analytics'
    | '/business/billing'
    | '/business/bookings'
    | '/business/customers'
    | '/business/notifications'
    | '/business/orders'
    | '/business/products'
    | '/business/reviews'
    | '/business/services'
    | '/business/settings'
    | '/business/storefront'
    | '/business/team'
    | '/businesses/$id'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/settings'
    | '/customer/support'
    | '/customer/wishlist'
    | '/products/$id'
    | '/services/$id'
    | '/admin/'
    | '/business/'
    | '/businesses/'
    | '/customer/'
    | '/products/'
    | '/services/'
    | '/customer/bookings/$id'
    | '/customer/checkout/success'
    | '/customer/orders/$id'
    | '/customer/bookings/'
    | '/customer/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/become-a-business'
    | '/categories'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/business/analytics'
    | '/business/billing'
    | '/business/bookings'
    | '/business/customers'
    | '/business/notifications'
    | '/business/orders'
    | '/business/products'
    | '/business/reviews'
    | '/business/services'
    | '/business/settings'
    | '/business/storefront'
    | '/business/team'
    | '/businesses/$id'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/settings'
    | '/customer/support'
    | '/customer/wishlist'
    | '/products/$id'
    | '/services/$id'
    | '/admin'
    | '/business'
    | '/businesses'
    | '/customer'
    | '/products'
    | '/services'
    | '/customer/bookings/$id'
    | '/customer/checkout/success'
    | '/customer/orders/$id'
    | '/customer/bookings'
    | '/customer/orders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/become-a-business'
    | '/business'
    | '/businesses'
    | '/categories'
    | '/contact'
    | '/cookies'
    | '/customer'
    | '/faq'
    | '/forgot-password'
    | '/login'
    | '/pricing'
    | '/privacy'
    | '/products'
    | '/reset-password'
    | '/search'
    | '/services'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin/analytics'
    | '/admin/bookings'
    | '/admin/businesses'
    | '/admin/categories'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/users'
    | '/business/analytics'
    | '/business/billing'
    | '/business/bookings'
    | '/business/customers'
    | '/business/notifications'
    | '/business/orders'
    | '/business/products'
    | '/business/reviews'
    | '/business/services'
    | '/business/settings'
    | '/business/storefront'
    | '/business/team'
    | '/businesses/$id'
    | '/customer/addresses'
    | '/customer/cart'
    | '/customer/checkout'
    | '/customer/notifications'
    | '/customer/profile'
    | '/customer/settings'
    | '/customer/support'
    | '/customer/wishlist'
    | '/products/$id'
    | '/services/$id'
    | '/admin/'
    | '/business/'
    | '/businesses/'
    | '/customer/'
    | '/products/'
    | '/services/'
    | '/customer/bookings/$id'
    | '/customer/checkout/success'
    | '/customer/orders/$id'
    | '/customer/bookings/'
    | '/customer/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomeABusinessRoute: typeof BecomeABusinessRoute
  BusinessRoute: typeof BusinessRouteWithChildren
  BusinessesRoute: typeof BusinessesRouteWithChildren
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  CustomerRoute: typeof CustomerRouteWithChildren
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer': {
      id: '/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof CustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/businesses': {
      id: '/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof BusinessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business': {
      id: '/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof BusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-a-business': {
      id: '/become-a-business'
      path: '/become-a-business'
      fullPath: '/become-a-business'
      preLoaderRoute: typeof BecomeABusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/customer/': {
      id: '/customer/'
      path: '/'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/businesses/': {
      id: '/businesses/'
      path: '/'
      fullPath: '/businesses/'
      preLoaderRoute: typeof BusinessesIndexRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/business/': {
      id: '/business/'
      path: '/'
      fullPath: '/business/'
      preLoaderRoute: typeof BusinessIndexRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof ProductsRoute
    }
    '/customer/wishlist': {
      id: '/customer/wishlist'
      path: '/wishlist'
      fullPath: '/customer/wishlist'
      preLoaderRoute: typeof CustomerWishlistRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/support': {
      id: '/customer/support'
      path: '/support'
      fullPath: '/customer/support'
      preLoaderRoute: typeof CustomerSupportRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/settings': {
      id: '/customer/settings'
      path: '/settings'
      fullPath: '/customer/settings'
      preLoaderRoute: typeof CustomerSettingsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/profile': {
      id: '/customer/profile'
      path: '/profile'
      fullPath: '/customer/profile'
      preLoaderRoute: typeof CustomerProfileRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/notifications': {
      id: '/customer/notifications'
      path: '/notifications'
      fullPath: '/customer/notifications'
      preLoaderRoute: typeof CustomerNotificationsRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/checkout': {
      id: '/customer/checkout'
      path: '/checkout'
      fullPath: '/customer/checkout'
      preLoaderRoute: typeof CustomerCheckoutRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/cart': {
      id: '/customer/cart'
      path: '/cart'
      fullPath: '/customer/cart'
      preLoaderRoute: typeof CustomerCartRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/addresses': {
      id: '/customer/addresses'
      path: '/addresses'
      fullPath: '/customer/addresses'
      preLoaderRoute: typeof CustomerAddressesRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/businesses/$id': {
      id: '/businesses/$id'
      path: '/$id'
      fullPath: '/businesses/$id'
      preLoaderRoute: typeof BusinessesIdRouteImport
      parentRoute: typeof BusinessesRoute
    }
    '/business/team': {
      id: '/business/team'
      path: '/team'
      fullPath: '/business/team'
      preLoaderRoute: typeof BusinessTeamRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/storefront': {
      id: '/business/storefront'
      path: '/storefront'
      fullPath: '/business/storefront'
      preLoaderRoute: typeof BusinessStorefrontRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/settings': {
      id: '/business/settings'
      path: '/settings'
      fullPath: '/business/settings'
      preLoaderRoute: typeof BusinessSettingsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/services': {
      id: '/business/services'
      path: '/services'
      fullPath: '/business/services'
      preLoaderRoute: typeof BusinessServicesRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/reviews': {
      id: '/business/reviews'
      path: '/reviews'
      fullPath: '/business/reviews'
      preLoaderRoute: typeof BusinessReviewsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/products': {
      id: '/business/products'
      path: '/products'
      fullPath: '/business/products'
      preLoaderRoute: typeof BusinessProductsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/orders': {
      id: '/business/orders'
      path: '/orders'
      fullPath: '/business/orders'
      preLoaderRoute: typeof BusinessOrdersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/notifications': {
      id: '/business/notifications'
      path: '/notifications'
      fullPath: '/business/notifications'
      preLoaderRoute: typeof BusinessNotificationsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/customers': {
      id: '/business/customers'
      path: '/customers'
      fullPath: '/business/customers'
      preLoaderRoute: typeof BusinessCustomersRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/bookings': {
      id: '/business/bookings'
      path: '/bookings'
      fullPath: '/business/bookings'
      preLoaderRoute: typeof BusinessBookingsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/billing': {
      id: '/business/billing'
      path: '/billing'
      fullPath: '/business/billing'
      preLoaderRoute: typeof BusinessBillingRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/business/analytics': {
      id: '/business/analytics'
      path: '/analytics'
      fullPath: '/business/analytics'
      preLoaderRoute: typeof BusinessAnalyticsRouteImport
      parentRoute: typeof BusinessRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/businesses': {
      id: '/admin/businesses'
      path: '/businesses'
      fullPath: '/admin/businesses'
      preLoaderRoute: typeof AdminBusinessesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/customer/orders/': {
      id: '/customer/orders/'
      path: '/orders'
      fullPath: '/customer/orders/'
      preLoaderRoute: typeof CustomerOrdersIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/bookings/': {
      id: '/customer/bookings/'
      path: '/bookings'
      fullPath: '/customer/bookings/'
      preLoaderRoute: typeof CustomerBookingsIndexRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/orders/$id': {
      id: '/customer/orders/$id'
      path: '/orders/$id'
      fullPath: '/customer/orders/$id'
      preLoaderRoute: typeof CustomerOrdersIdRouteImport
      parentRoute: typeof CustomerRoute
    }
    '/customer/checkout/success': {
      id: '/customer/checkout/success'
      path: '/success'
      fullPath: '/customer/checkout/success'
      preLoaderRoute: typeof CustomerCheckoutSuccessRouteImport
      parentRoute: typeof CustomerCheckoutRoute
    }
    '/customer/bookings/$id': {
      id: '/customer/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/customer/bookings/$id'
      preLoaderRoute: typeof CustomerBookingsIdRouteImport
      parentRoute: typeof CustomerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBookingsRoute: typeof AdminBookingsRoute
  AdminBusinessesRoute: typeof AdminBusinessesRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBookingsRoute: AdminBookingsRoute,
  AdminBusinessesRoute: AdminBusinessesRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BusinessRouteChildren {
  BusinessAnalyticsRoute: typeof BusinessAnalyticsRoute
  BusinessBillingRoute: typeof BusinessBillingRoute
  BusinessBookingsRoute: typeof BusinessBookingsRoute
  BusinessCustomersRoute: typeof BusinessCustomersRoute
  BusinessNotificationsRoute: typeof BusinessNotificationsRoute
  BusinessOrdersRoute: typeof BusinessOrdersRoute
  BusinessProductsRoute: typeof BusinessProductsRoute
  BusinessReviewsRoute: typeof BusinessReviewsRoute
  BusinessServicesRoute: typeof BusinessServicesRoute
  BusinessSettingsRoute: typeof BusinessSettingsRoute
  BusinessStorefrontRoute: typeof BusinessStorefrontRoute
  BusinessTeamRoute: typeof BusinessTeamRoute
  BusinessIndexRoute: typeof BusinessIndexRoute
}

const BusinessRouteChildren: BusinessRouteChildren = {
  BusinessAnalyticsRoute: BusinessAnalyticsRoute,
  BusinessBillingRoute: BusinessBillingRoute,
  BusinessBookingsRoute: BusinessBookingsRoute,
  BusinessCustomersRoute: BusinessCustomersRoute,
  BusinessNotificationsRoute: BusinessNotificationsRoute,
  BusinessOrdersRoute: BusinessOrdersRoute,
  BusinessProductsRoute: BusinessProductsRoute,
  BusinessReviewsRoute: BusinessReviewsRoute,
  BusinessServicesRoute: BusinessServicesRoute,
  BusinessSettingsRoute: BusinessSettingsRoute,
  BusinessStorefrontRoute: BusinessStorefrontRoute,
  BusinessTeamRoute: BusinessTeamRoute,
  BusinessIndexRoute: BusinessIndexRoute,
}

const BusinessRouteWithChildren = BusinessRoute._addFileChildren(
  BusinessRouteChildren,
)

interface BusinessesRouteChildren {
  BusinessesIdRoute: typeof BusinessesIdRoute
  BusinessesIndexRoute: typeof BusinessesIndexRoute
}

const BusinessesRouteChildren: BusinessesRouteChildren = {
  BusinessesIdRoute: BusinessesIdRoute,
  BusinessesIndexRoute: BusinessesIndexRoute,
}

const BusinessesRouteWithChildren = BusinessesRoute._addFileChildren(
  BusinessesRouteChildren,
)

interface CustomerCheckoutRouteChildren {
  CustomerCheckoutSuccessRoute: typeof CustomerCheckoutSuccessRoute
}

const CustomerCheckoutRouteChildren: CustomerCheckoutRouteChildren = {
  CustomerCheckoutSuccessRoute: CustomerCheckoutSuccessRoute,
}

const CustomerCheckoutRouteWithChildren =
  CustomerCheckoutRoute._addFileChildren(CustomerCheckoutRouteChildren)

interface CustomerRouteChildren {
  CustomerAddressesRoute: typeof CustomerAddressesRoute
  CustomerCartRoute: typeof CustomerCartRoute
  CustomerCheckoutRoute: typeof CustomerCheckoutRouteWithChildren
  CustomerNotificationsRoute: typeof CustomerNotificationsRoute
  CustomerProfileRoute: typeof CustomerProfileRoute
  CustomerSettingsRoute: typeof CustomerSettingsRoute
  CustomerSupportRoute: typeof CustomerSupportRoute
  CustomerWishlistRoute: typeof CustomerWishlistRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  CustomerBookingsIdRoute: typeof CustomerBookingsIdRoute
  CustomerOrdersIdRoute: typeof CustomerOrdersIdRoute
  CustomerBookingsIndexRoute: typeof CustomerBookingsIndexRoute
  CustomerOrdersIndexRoute: typeof CustomerOrdersIndexRoute
}

const CustomerRouteChildren: CustomerRouteChildren = {
  CustomerAddressesRoute: CustomerAddressesRoute,
  CustomerCartRoute: CustomerCartRoute,
  CustomerCheckoutRoute: CustomerCheckoutRouteWithChildren,
  CustomerNotificationsRoute: CustomerNotificationsRoute,
  CustomerProfileRoute: CustomerProfileRoute,
  CustomerSettingsRoute: CustomerSettingsRoute,
  CustomerSupportRoute: CustomerSupportRoute,
  CustomerWishlistRoute: CustomerWishlistRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  CustomerBookingsIdRoute: CustomerBookingsIdRoute,
  CustomerOrdersIdRoute: CustomerOrdersIdRoute,
  CustomerBookingsIndexRoute: CustomerBookingsIndexRoute,
  CustomerOrdersIndexRoute: CustomerOrdersIndexRoute,
}

const CustomerRouteWithChildren = CustomerRoute._addFileChildren(
  CustomerRouteChildren,
)

interface ProductsRouteChildren {
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesIdRoute: typeof ServicesIdRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIdRoute: ServicesIdRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomeABusinessRoute: BecomeABusinessRoute,
  BusinessRoute: BusinessRouteWithChildren,
  BusinessesRoute: BusinessesRouteWithChildren,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  CustomerRoute: CustomerRouteWithChildren,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
